# Generated by Django 5.0.4 on 2025-01-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_role_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
