# Generated by Django 5.0.4 on 2025-01-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_orderproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='size',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='total_price',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='total_size',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='unit_price',
            field=models.PositiveIntegerField(),
        ),
    ]
